name = "Minecraft 3 - Convoluted naming sheme: Beach episode"
author = "strosel"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20943853a89b6951c49812505794ca891616d7aff064764cfcf666d250491106"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
