name = "Minecraft 3 - Convoluted naming sheme: Beach episode"
author = "strosel"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a02d1423f00cd52b1841dee607ae17a17282811c2a9a3bbadd8c1f7eaad80a0b"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
