name = "Minecraft 3 - Convoluted naming sheme: Beach episode"
author = "strosel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5965f7d6d68979f30117d405ddb5965fabf1871e573536985422442fceb17c77"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
