name = "Minecraft 3 - Convoluted naming sheme: Beach episode"
mc_version = "1.20.1"

[jar]
type = "forge"
loader = "47.3.22"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "HXF82T3G"
version = "BoqlF2eH"

[[mods]]
type = "modrinth"
id = "BpwWFOVM"
version = "EM7Su3PD"

[[mods]]
type = "modrinth"
id = "Wnxd13zP"
version = "nAHGB5ls"

[[mods]]
type = "modrinth"
id = "gBGdVBJy"
version = "wTljl54O"

[[mods]]
type = "modrinth"
id = "Cq0m2EIu"
version = "joFfuMtv"

[[mods]]
type = "modrinth"
id = "uCdwusMi"
version = "20nF6i21"

[[mods]]
type = "modrinth"
id = "R2OftAxM"
version = "MG1Xuspn"

[[mods]]
type = "modrinth"
id = "s3dmwKy5"
version = "pYPZ5MNI"

[[mods]]
type = "modrinth"
id = "uHWrqYcS"
version = "kVfMYM11"

[[mods]]
type = "modrinth"
id = "nvQzSEkH"
version = "bzWVE2db"

[[mods]]
type = "modrinth"
id = "zfbCkvdZ"
version = "er56DwLJ"

[[mods]]
type = "modrinth"
id = "QAGBst4M"
version = "2qznQtPr"

[[mods]]
type = "modrinth"
id = "e0bNACJD"
version = "FW4WSjtn"

[[mods]]
type = "modrinth"
id = "kkmrDlKT"
version = "HI0iCUpi"

[[mods]]
type = "modrinth"
id = "2cMuAZAp"
version = "XoIASRVU"

[[mods]]
type = "modrinth"
id = "EsAfCjCV"
version = "XdXDExVF"

[[mods]]
type = "modrinth"
id = "lhGA9TYQ"
version = "1MKTLiiG"

[[mods]]
type = "modrinth"
id = "bb2EpKpx"
version = "r0eKAc5z"

[[mods]]
type = "modrinth"
id = "P0Mu4wcQ"
version = "LkhH2gKX"

[[mods]]
type = "modrinth"
id = "rqIsPf9F"
version = "46g3IiWw"

[[mods]]
type = "modrinth"
id = "hSowj7sJ"
version = "xt62WCTA"

[[mods]]
type = "modrinth"
id = "fEWKxVzh"
version = "vtGe3auv"

[[mods]]
type = "modrinth"
id = "oiuNWinn"
version = "k0HGRziM"

[[mods]]
type = "modrinth"
id = "jJfV67b1"
version = "a7H8TGhJ"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "t8TXrZvZ"

[[mods]]
type = "modrinth"
id = "vvuO3ImH"
version = "QBtodtmR"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "DG5Fn9Sz"

[[mods]]
type = "modrinth"
id = "8BmcQJ2H"
version = "LwI6czff"

[[mods]]
type = "modrinth"
id = "pJmCFF0p"
version = "N7wZwOFy"

[[mods]]
type = "modrinth"
id = "x3HZvrj6"
version = "hZ6Uu1Ny"

[[mods]]
type = "modrinth"
id = "TaSmHw8V"
version = "zjMy2oFH"

[[mods]]
type = "modrinth"
id = "OuJDwbIs"
version = "V5qgYPzs"

[[mods]]
type = "modrinth"
id = "u6dRKJwZ"
version = "iNv5B1Zj"

[[mods]]
type = "modrinth"
id = "ordsPcFz"
version = "hmeyC41q"

[[mods]]
type = "modrinth"
id = "4d7eGKIA"
version = "jV0VgbO3"

[[mods]]
type = "modrinth"
id = "5uSvd1Ca"
version = "sRzAmAjJ"

[[mods]]
type = "modrinth"
id = "GURcjz8O"
version = "wJ0BHouQ"

[[mods]]
type = "modrinth"
id = "kNxa8z3e"
version = "Osvj0z4A"

[[mods]]
type = "modrinth"
id = "GmwLse2I"
version = "1wrqNArj"

[[mods]]
type = "modrinth"
id = "dtWC90iB"
version = "jQcvCX79"

[[mods]]
type = "modrinth"
id = "w4an97C2"
version = "zedTvpc3"

[[mods]]
type = "modrinth"
id = "okE6QVAY"
version = "yaSdsps0"

[[mods]]
type = "modrinth"
id = "VRLhWB91"
version = "fznFN68i"

[[mods]]
type = "modrinth"
id = "B8jaH3P1"
version = "9Q45nZes"

[[mods]]
type = "modrinth"
id = "iP3wH1ha"
version = "mlrXeKjs"

[[mods]]
type = "modrinth"
id = "n2fvCDlM"
version = "eyOMFyxY"

[[mods]]
type = "modrinth"
id = "C7I0BCni"
version = "GhYHduKi"

[[mods]]
type = "modrinth"
id = "Tanquv9C"
version = "POJtavWu"

[[mods]]
type = "modrinth"
id = "XQ6CZtXV"
version = "IZ7xhuAb"

[[mods]]
type = "modrinth"
id = "DGiq4ZSW"
version = "9jLLNENb"

[[mods]]
type = "modrinth"
id = "M1953qlQ"
version = "irREd1ZJ"

[[mods]]
type = "modrinth"
id = "G1hIVOrD"
version = "OhsHaCcW"

[[mods]]
type = "modrinth"
id = "iSkQCp6b"
version = "PH3QFp5w"

[[mods]]
type = "modrinth"
id = "bK3Ubu9p"
version = "OFYmngee"

[[mods]]
type = "modrinth"
id = "rGWEHQrP"
version = "58DKgNnY"

[[mods]]
type = "modrinth"
id = "TyCTlI4b"
version = "zkb0vOdU"

[[mods]]
type = "modrinth"
id = "nmoqTijg"
version = "FolEFTVg"

[[mods]]
type = "curserinth"
id = "556448"
version = "5028450"

[[mods]]
type = "curserinth"
id = "227875"
version = "5470117"

[[mods]]
type = "curserinth"
id = "549225"
version = "5911986"

[[mods]]
type = "curserinth"
id = "902986"
version = "5733302"

[[mods]]
type = "modrinth"
id = "nfn13YXA"
version = "IoS2AjPk"
